### ISSUE TITLE
Uncaught DOMException: Failed to construct 'Worker': Script at 'file:///Users/dassintern/Documents/ayash/csv-to-xapi-master/js/lib/papaparse.min.js?papaworker' cannot be accessed from origin 'null'.

### ISSUE THREAD

**Issue by Ayash18** [liris-tweak/csv-to-xapi#1]
I have been trying to do some research on xAPI statement and found this quite interesting. But following the mention steps. I tried to upload the CSV file but come up with the error in papaparse.mini.js. i am just trying to fletch the CSV data with the help of xAPI lAb to develop statement from CSV file and communicate it with  LRS.

**Comment by pchampin** [comment]
First guess: the problem comes from the `file:///` URL. There are a number of things that do not work with `file:///` URLs, and workers might very well be one of them. Also, the part of the message about "origin 'null'" tends to confirm that hunch.

Try running a local HTTP server and access the application through a `http://localhost` URL, and see if the problem still happens.

**Comment by Ayash18** [comment]
Well Thank you, it's working now.
